# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aee285c04bc81f5484bbbe5f0faa1713a6d749140c5bc73d08f0bb03b75455f0ebb1dfbc568e45a32b29dedaa201295c1ffa008c28ff9cf2886e37f092fe58b7

test:
  secret_key_base: eb27faf157ddd6d10ae7db08f527a9f009cdcca79ff4f11d68f2492c0143b1a3e1f0a7aca54c1cc6f22ff596177a9d5c943aa7a2574ddfdf6ec0d4ee13645a26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
